#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define MQ_KEY 10101
#define MQ_ID_MAIN_SERVER 3

#define MSG_TARGET_SIGN_UP 0
#define MSG_TARGET_SIGN_IN 1
#define MSG_TARGET_CHATTING 2
#define MSG_TARGET_CREATE_ROOM 3
#define MSG_TARGET_JOIN_ROOM 4
#define MSG_TARGET_CHECK_LOBBY 5
#define MSG_TARGET_CHECK_ROOM 10
#define MSG_TARGET_GAME_START 6
#define MSG_TARGET_LEAVE_ROOM 8
#define MSG_TARGET_QUIT 9

#define RESULT_OK_SIGN_IN 1001
#define RESULT_OK_CREATE_ROOM 1004
#define RESULT_OK_REQUEST_LOBBY_UPDATE 1005
#define RESULT_OK_JOIN_ROOM 1006
#define RESULT_OK_REQUEST_ROOM_MEMBER_UPDATE 1007
#define RESULT_OK_STATE_LOBBY 1008
#define RESULT_OK_GAME_START 1010

#define RESULT_ERROR_INVALID_AUTH 2001
#define RESULT_ERROR_INVALID_CONNECTION 2002

#define USER_STATUS_LOBBY 0
#define USER_STATUS_IN_ROOM 1

#define GAME_ROOM_STATUS_READY 0
#define GAME_ROOM_STATUS_PLAYING 1
#define GAME_ROOM_STATUS_SHOWING_ROUND_RESULT 2
#define GAME_ROOM_STATUS_SHOWING_TOTAL_RESULT 3


#endif