#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define MQ_KEY 10101
#define MQ_ID_MAIN_SERVER 3

#define MSG_TARGET_SIGN_UP 0
#define MSG_TARGET_SIGN_IN 1
#define MSG_TARGET_CHATTING 2
#define MSG_TARGET_CREATE_ROOM 3
#define MSG_TARGET_JOIN_ROOM 4
#define MSG_TARGET_CHECK_ROBBY 5
#define MSG_TARGET_CHECK_ROOM 10
#define MSG_TARGET_GAME_START 6
#define MSG_TARGET_LEAVE_ROOM 8
#define MSG_TARGET_QUIT 9

#define USER_STATUS_LOBBY 0
#define USER_STATUS_IN_ROOM 1

#endif